### ISSUE TITLE
Scipy needed

### ISSUE THREAD

**Issue by CatChenal** [GunnerLab/Stable-MCCE#281]
As per error message:
```
(base) cchenal@isis:~/projects/mcce_benchmarks/clean_pdbs/1I0E$ tail run.log
Traceback (most recent call last):
  File "/home/mcce/Stable-MCCE/bin/step3.py", line 43, in <module>
    from vdw_pw import *
  File "/data/home/mcce/Stable-MCCE/bin/vdw_pw.py", line 7, in <module>
    from pdbio import *
  File "/data/home/mcce/Stable-MCCE/bin/pdbio.py", line 9, in <module>
    from scipy.sparse import lil_matrix
ModuleNotFoundError: No module named 'scipy'
```

**Comment by CatChenal** [comment]
This is not a MCCE bug: this is a "user environment error" (mine!).
Context:
I tried to manually rerun a single failing protein while unaware my dedicated environment for benchmarking wasn't activated & thus I was using my conda "base" environment, which is minimal (& should stay so).
